#!/usr/bin/env python3
"""
Build an RSS 2.0 feed for offline share (stdlib only).

  python scripts/rss_share.py items.json -o workspace/feed.xml
  python scripts/rss_share.py items.json --title "Fable notes" --link https://example.com/
  python scripts/rss_share.py --demo -o workspace/demo-feed.xml

items.json shape:
{
  "title": "Channel title",
  "link": "https://example.com/",
  "description": "Channel description",
  "language": "en-nz",
  "items": [
    {
      "title": "Post title",
      "link": "https://example.com/p/1",
      "description": "HTML or plain summary",
      "guid": "optional-stable-id",
      "pubDate": "2026-07-13T12:00:00Z",
      "author": "optional",
      "category": "optional or [\"a\",\"b\"]"
    }
  ]
}
"""
from __future__ import annotations

import argparse
import html
import json
import sys
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, ElementTree


def parse_pubdate(raw: str | None) -> str:
    if not raw:
        return format_datetime(datetime.now(timezone.utc))
    raw = raw.strip()
    # Already RFC 822-ish
    if "," in raw and ("GMT" in raw or "+" in raw or "-" in raw[-5:]):
        return raw
    try:
        if raw.endswith("Z"):
            dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        else:
            dt = datetime.fromisoformat(raw)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return format_datetime(dt)
    except ValueError:
        return format_datetime(datetime.now(timezone.utc))


def text_el(parent: Element, tag: str, text: str) -> Element:
    el = SubElement(parent, tag)
    el.text = text
    return el


def build_rss(channel: dict) -> Element:
    rss = Element("rss", version="2.0")
    # Optional Atom self-link compatibility is out of scope; pure RSS 2.0
    ch = SubElement(rss, "channel")
    text_el(ch, "title", str(channel.get("title") or "Untitled feed"))
    text_el(ch, "link", str(channel.get("link") or "https://example.invalid/"))
    text_el(ch, "description", str(channel.get("description") or ""))
    if channel.get("language"):
        text_el(ch, "language", str(channel["language"]))
    text_el(
        ch,
        "lastBuildDate",
        parse_pubdate(channel.get("lastBuildDate")),
    )
    text_el(ch, "generator", "Fable Offline rss_share.py")

    items = channel.get("items") or []
    for it in items:
        item = SubElement(ch, "item")
        title = str(it.get("title") or "Untitled")
        link = str(it.get("link") or channel.get("link") or "")
        desc = str(it.get("description") or "")
        text_el(item, "title", title)
        if link:
            text_el(item, "link", link)
        # description may contain markup; escape to keep well-formed XML unless raw_html
        if it.get("raw_html"):
            d = SubElement(item, "description")
            d.text = desc
        else:
            text_el(item, "description", html.escape(desc))
        guid_val = str(it.get("guid") or link or title)
        guid = SubElement(item, "guid")
        guid.set("isPermaLink", "true" if (link and guid_val == link) else "false")
        guid.text = guid_val
        text_el(item, "pubDate", parse_pubdate(it.get("pubDate")))
        if it.get("author"):
            text_el(item, "author", str(it["author"]))
        cat = it.get("category")
        if isinstance(cat, list):
            for c in cat:
                text_el(item, "category", str(c))
        elif cat:
            text_el(item, "category", str(cat))
    return rss


def write_rss(root: Element, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tree = ElementTree(root)
    # declaration
    tree.write(path, encoding="utf-8", xml_declaration=True)


def demo_channel() -> dict:
    return {
        "title": "Fable Offline - demo share",
        "link": "https://github.com/dglogan42/Fable-Offline",
        "description": "Demo RSS channel generated by scripts/rss_share.py",
        "language": "en",
        "items": [
            {
                "title": "Demo item",
                "link": "https://github.com/dglogan42/Fable-Offline",
                "description": "Replace with your notes. Skill: rss-share.",
                "pubDate": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "category": ["fable", "demo"],
            }
        ],
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build RSS 2.0 feed for share")
    ap.add_argument("items", nargs="?", type=Path, help="Path to channel JSON")
    ap.add_argument("-o", "--out", type=Path, default=Path("workspace/feed.xml"))
    ap.add_argument("--title", help="Override channel title")
    ap.add_argument("--link", help="Override channel link")
    ap.add_argument("--description", help="Override channel description")
    ap.add_argument("--demo", action="store_true", help="Write demo feed")
    ap.add_argument("--stdout", action="store_true", help="Print XML to stdout")
    args = ap.parse_args(argv)

    if args.demo:
        channel = demo_channel()
    elif args.items and args.items.is_file():
        channel = json.loads(args.items.read_text(encoding="utf-8"))
        if not isinstance(channel, dict):
            print("JSON root must be an object (channel)", file=sys.stderr)
            return 1
        # Allow bare list of items
        if "items" not in channel and isinstance(channel.get("entries"), list):
            channel["items"] = channel.pop("entries")
    else:
        print("Provide items.json or --demo", file=sys.stderr)
        return 1

    if args.title:
        channel["title"] = args.title
    if args.link:
        channel["link"] = args.link
    if args.description:
        channel["description"] = args.description

    root = build_rss(channel)
    if args.stdout:
        import io

        buf = io.BytesIO()
        ElementTree(root).write(buf, encoding="utf-8", xml_declaration=True)
        sys.stdout.buffer.write(buf.getvalue())
        if not buf.getvalue().endswith(b"\n"):
            sys.stdout.buffer.write(b"\n")
    else:
        write_rss(root, args.out)
        print(f"Wrote {args.out} ({len(channel.get('items') or [])} items)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
